name: Release NPM

on:
  push:
    tags:
      - '*'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.23
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

permissions:
  contents: write
  discussions: write

jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Build
        run: make build-all-platforms

      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            LICENSE
            build/slack-mcp-server-*
            .env.dist
            docker-compose.yml

      - name: Publish npm
        run:
          make npm-publish
